### ISSUE TITLE
Wrong data in run details

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#114]
After a run is finished, the "run details" below the plot always states "Best model quality: 0.0" and
"Current generation: 0". Correct it.

**Comment by leichenxu** [comment]
should be fixed in https://github.com/GRAFO-URJC/WebGE/commit/7c517c85f6af011c2879f428530c1302deb6afd0
changed the form of ordering diagram data
i can't recreate the problem now
@jmcolmenar check it

**Comment by jmcolmenar** [comment]
Still not working...

![Captura de pantalla 2020-06-19 a las 9 57 08](https://user-images.githubusercontent.com/4963260/85110535-5b0e2d80-b213-11ea-880a-8a79b83e0080.png)
